## ?? ?? ??
server:
  port: 8088

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

## ??? ???? ??
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521:orcl
    username: C##HR_SYSTEM
    password: HR_SYSTEM
    hikari:
      auto-commit: false

  jpa:
    generate-ddl: false
    show-sql: true
    database: oracle
    properties:
      hibernate:
        '[format_sql]': true

  logging:
    level:
      root: error
  
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      