sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t keaunsol/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true keaunsol/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-972153559337"
  bucket_path: "docker-react"
  on:
    branch: master
    
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRECT_ACCESS_KEY