CREATE USER C##SCHOOL IDENTIFIED BY SCHOOL;                           
GRANT CONNECT, RESOURCE, CREATE VIEW TO C##SCHOOL;  

ALTER USER C##SCHOOL DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS; 
ALTER USER C##SCHOOL QUOTA 1024M ON SYSTEM; 