DROP TABLE CLASS_DIVISION;
DROP TABLE TEACHER_INFO;
DROP TABLE CLASS_INFO;

CREATE TABLE CLASS_DIVISION
(
  DIVISION_NO NUMBER CONSTRAINT PK_DIVISION_NO PRIMARY KEY 
, DIVISION_NAME VARCHAR2(30) CONSTRAINT NN_DIVISION_NAME NOT NULL    
);

COMMENT ON COLUMN CLASS_DIVISION.DIVISION_NO IS '학년구분번호';
COMMENT ON COLUMN CLASS_DIVISION.DIVISION_NAME IS '구분 이름';

INSERT INTO CLASS_DIVISION VALUES (1, '1학년');
INSERT INTO CLASS_DIVISION VALUES (2, '1학년 진학반');
INSERT INTO CLASS_DIVISION VALUES (3, '문과');
INSERT INTO CLASS_DIVISION VALUES (4, '문과 진학반');
INSERT INTO CLASS_DIVISION VALUES (5, '이과');
INSERT INTO CLASS_DIVISION VALUES (6, '이과 진학반');
INSERT INTO CLASS_DIVISION VALUES (7, '졸업생');

CREATE TABLE TEACHER_INFO
(
  TEACHER_NO NUMBER CONSTRAINT PK_TEACHER_NO PRIMARY KEY
, TEACHER_NAME VARCHAR2(30) CONSTRAINT NN_TEACHER_NAME NOT NULL
, TEACHER_PHONE VARCHAR2(30) CONSTRAINT NN_TEACHER_PHONE NOT NULL
, TEACHER_YEARLY NUMBER CONSTRAINT NN_TEACHER_YEARLY NOT NULL
, TEACHER_DROP_YN VARCHAR2(3) DEFAULT 'N' CONSTRAINT NN_TEACHER_DROP_YN NOT NULL
, TEACHER_SALARY NUMBER CONSTRAINT NN_TEACHER_SALARY NOT NULL
, CONSTRAINT CK_TEACHER_DROP_YN CHECK (TEACHER_DROP_YN IN ('Y','N'))
, CONSTRAINT CK_TEACHER_SALARY CHECK (TEACHER_SALARY > 0)
);


CREATE TABLE CLASS_INFO
(
  CLASS_NO NUMBER 
, CLASS_DIVISION_NO NUMBER CONSTRAINT NN_CLASS_DIVISION_NO NOT NULL
, CLASS_TEACHER_NO  NUMBER CONSTRAINT NN_CLASS_TEACHER_NO NOT NULL
, CLASS_CAPACITY NUMBER CONSTRAINT NN_CLASS_CAPACITY NOT NULL
, CONSTRAINT FK_CLASS_DIVISION_NO FOREIGN KEY (CLASS_DIVISION_NO)
                                  REFERENCES CLASS_DIVISION(DIVISION_NO)
, CONSTRAINT PFK_CLASS_NO_CLASS_DIVISION_NO PRIMARY KEY(CLASS_NO, CLASS_DIVISION_NO)                                 
, CONSTRAINT FK_CLASS_TEACHER_NO FOREIGN KEY (CLASS_TEACHER_NO) 
                                 REFERENCES TEACHER_INFO(TEACHER_NO)
);

COMMENT ON COLUMN CLASS_INFO.CLASS_NO IS '반번호';
COMMENT ON COLUMN CLASS_INFO.CLASS_DIVISION_NO IS '반구분번호';
COMMENT ON COLUMN CLASS_INFO.CLASS_TEACHER_NO IS '담임교사번호';
COMMENT ON COLUMN CLASS_INFO.CLASS_CAPACITY IS '반정원';