CREATE USER C##FINAL IDENTIFIED BY FINAL;                           
GRANT CONNECT, RESOURCE TO C##FINAL;                                           

GRANT CONNECT TO C##FINAL;
GRANT RESOURCE TO C##FINAL;
GRANT CREATE VIEW TO C##FINAL;   
GRANT CREATE SYNONYM TO C##FINAL; 

ALTER USER C##FINAL DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS; 
ALTER USER C##FINAL QUOTA 1024M ON SYSTEM; 